### ISSUE TITLE
Support disabling finders

### ISSUE THREAD

**Issue by skeggse** [StreakYC/page-parser-tree#6]
We've got some finders that only need to run until they discover an element, at which point we trust that the element will remain static for all eternity. As a result, we'd like to be able to disable a finder dynamically. Previously, we were doing this by using the following `interval` function:

```js
singletonNode: {
  ...,
  interval: (nodesFound) => nodesFound ? Infinity : 5000,
}
```

It turns out that using `Infinity` as the interval actually causes substantial CPU usage (30-40% on a 2017 macbook), at least on the latest Chrome/macOS. Passing some very large value instead causes a ~30x drop in CPU utilization, measured over a full minute.

Can we add support for using `Infinity` (or some other sentinel value) to disable a finder (but not the underlying tag)?

**Comment by Macil** [comment]
The returned value is immediately given to `setTimeout`, which treats Infinity as 0.

I've made that same mistake too. I'll make page-parser-tree handle Infinity.

In the InboxSDK, we use a pattern like this often to make us lay off on the finder for elements that we usually expect there to be one of on the page immediately, and then be static for all time:

```
      interval: (count, timeRunning) => (
        (count === 0 && timeRunning < 60*1000) ? 300 : 2*60*1000
      )
```

(I've thought about whether the API should have some simpler more declarative option to be used in situations like this, but I haven't come up with any one-size-fits-all ideas, and I'd rather not clutter up the API with options that are purely redundant with interval.)

**Comment by Macil** [comment]
Version 0.3.5 on npm stops running the finder when given Infinity.
